#!/usr/bin/env python3
"""
scan-issues.py — Scan docs/ for structural/conversion issues.

Issue categories:
  XREF      [???](…) unresolved cross-reference from pandoc
  ARTIFACT  pandoc placeholder: [step_title], [varlistentry_title], formalpara-title
  SYNOPSIS  concatenated command sequence outside a code block (<synopsis> collapse)
  FUNCDEF   C function signature merged with prose description (func(); description)
  LONGLINE  prose line > LONGLINE_THRESH chars (likely unsplit or collapsed block)

Output: grouped by file, sorted by path.

Usage:
    python3 scan-issues.py                    # all files, all categories
    python3 scan-issues.py --only XREF,FUNCDEF
    python3 scan-issues.py path/to/file.md    # single file
    python3 scan-issues.py --summary          # counts only, no line details
"""

import os, re, sys

DOCS            = os.path.join(os.path.dirname(__file__), 'docs')
LONGLINE_THRESH = 400   # chars; prose lines longer than this are flagged

# ── Pattern definitions ────────────────────────────────────────────────────────

# XREF: [???] anywhere (broken pandoc cross-reference)
_XREF_RE = re.compile(r'\[\?\?\?\]')

# ARTIFACT: known pandoc placeholder tokens
_ARTIFACT_RE = re.compile(
    r'\[step_title\]'
    r'|\[varlistentry_title\]'
    r'|\[listitem_title\]'
    r'|\[term_title\]'
    r'|:::\s*formalpara-title'
    r'|::: formalpara'
)

# SYNOPSIS: a non-code prose line that looks like concatenated shell commands.
# Signal: starts with a command token OR contains 4+ distinct command tokens.
_CMD_TOKEN = re.compile(
    r'\b(make|configure|meson|ninja|adduser|mkdir|chown|initdb|pg_ctl|'
    r'createdb|psql|pg_dump|pg_restore|pg_ctl|pg_upgrade|vacuumdb|'
    r'reindexdb|clusterdb|dropdb|createuser|dropuser)\b'
    r'|^\./\w'     # starts with ./something
    r'|^su\s'      # bare su command
)
_CMD_START = re.compile(
    r'^\./'         # ./configure etc.
    r'|^make\s'     # make install etc.
    r'|^ninja\s'    # ninja install etc.
    r'|^meson\s'    # meson setup etc.
)

def _is_synopsis(line: str) -> bool:
    """Heuristic: line is a collapsed <synopsis> or <screen> block."""
    s = line.strip()
    if not s or s.startswith('#') or s.startswith('|'):
        return False
    # Must start with a command-like token
    if not _CMD_START.match(s):
        return False
    # Must have 4+ command tokens (it's a list of commands, not prose about one)
    return len(_CMD_TOKEN.findall(s)) >= 4

# BROKEN_ANCHOR: local (#fragment) link that is probably a broken cross-page ref.
# Catches: [text](#non-guc-anchor) that aren't known in-page section slugs.
# Heuristic: flag links to anchors that look like DocBook IDs (contain a hyphen
# and don't look like heading slugs generated by goldmark from the page's own headings).
# We flag: #guc-*, #runtime-config-*, table anchors (*-table), figure anchors (*-fig),
# and any [foo_title](#id) leftover artifact.
_BROKEN_ANCHOR_RE = re.compile(
    r'\[[^\]]+\]\(#(?:'
    r'guc-[a-z0-9_-]+'           # GUC param refs
    r'|[a-z][a-z0-9-]+-table'    # *-table anchor (figure table ref)
    r'|[a-z][a-z0-9-]+-fig'      # *-fig anchor
    r'|[a-z][a-z0-9-]+-example'  # *-example anchor
    r'|runtime-config-[a-z0-9_-]+' # runtime-config section refs
    r'|[a-z_]+_title'            # *_title artifact
    r')\)'
)

# FUNCDEF: C function signature merged with prose.
# e.g. "Oid lo_create(PGconn *conn, Oid lobjId); creates a new large object."
_FUNCDEF_RE = re.compile(
    r'^(Oid|int|void|bool|char\s*\*|unsigned\s+int|size_t|ssize_t|'
    r'PGconn|PGresult|PGnotify|ExecStatusType|ConnStatusType|'
    r'PostgresPollingStatusType|PGTransactionStatusType)\s+'
    r'\w+\s*\([^)]*\)\s*;'   # func(params);
    r'.{10,}'                 # followed by description text (>10 chars)
)


# ── State machine helpers ──────────────────────────────────────────────────────

_FENCE_RE        = re.compile(r'^(`{3,}|~{3,})')
_DIRECTIVE_OPEN  = re.compile(r'^:::[^:\s]|^:::\{')
_DIRECTIVE_CLOSE = re.compile(r'^:::\s*$')
_LIST_ITEM       = re.compile(r'^\s*([-*+]|\d+[.)]) ')
_DEF_LIST        = re.compile(r'^:   ')


def _is_code_context(line: str) -> bool:
    s = line.rstrip()
    return (
        s.startswith('    ')
        or s.startswith('\t')
        or bool(_LIST_ITEM.match(s))
        or bool(_DEF_LIST.match(s))
    )


# ── Scanner ────────────────────────────────────────────────────────────────────

Issue = tuple[str, int, str, str]   # (category, lineno, line, file_rel)


def scan_file(path: str, docs_root: str) -> list[Issue]:
    rel = os.path.relpath(path, docs_root)
    issues: list[Issue] = []

    with open(path) as f:
        lines = f.readlines()

    in_frontmatter = False
    in_fence       = False
    in_directive   = False

    for i, line in enumerate(lines, 1):
        s = line.rstrip()

        # ── Frontmatter ──────────────────────────────────────────────────────
        if i == 1 and s == '---':
            in_frontmatter = True
            continue
        if in_frontmatter:
            if s == '---':
                in_frontmatter = False
            continue

        # ── Code fence ───────────────────────────────────────────────────────
        if _FENCE_RE.match(s):
            in_fence = not in_fence
            continue
        if in_fence:
            continue

        # ── Directive block (pass-through, but still scan for artifacts) ─────
        if _DIRECTIVE_OPEN.match(s):
            in_directive = True
            continue
        if _DIRECTIVE_CLOSE.match(s):
            in_directive = False
            continue
        if in_directive:
            # Artifacts can still appear inside directives
            if _XREF_RE.search(s):
                issues.append(('XREF', i, s, rel))
            if _ARTIFACT_RE.search(s):
                issues.append(('ARTIFACT', i, s, rel))
            continue

        # ── Headings / tables: check for artifacts only ───────────────────────
        if s.startswith('#') or s.startswith('|'):
            if _XREF_RE.search(s):
                issues.append(('XREF', i, s, rel))
            continue

        # ── Indented code / list items: check for artifacts only ─────────────
        if _is_code_context(line):
            if _XREF_RE.search(s):
                issues.append(('XREF', i, s, rel))
            if _ARTIFACT_RE.search(s):
                issues.append(('ARTIFACT', i, s, rel))
            continue

        # ── Blank lines ───────────────────────────────────────────────────────
        if not s:
            continue

        # ── Prose line: full checks ───────────────────────────────────────────
        if _XREF_RE.search(s):
            issues.append(('XREF', i, s, rel))

        if _ARTIFACT_RE.search(s):
            issues.append(('ARTIFACT', i, s, rel))

        if _is_synopsis(s):
            issues.append(('SYNOPSIS', i, s, rel))

        if _FUNCDEF_RE.match(s):
            issues.append(('FUNCDEF', i, s, rel))

        if _BROKEN_ANCHOR_RE.search(s):
            issues.append(('BROKEN_ANCHOR', i, s, rel))

        if len(s) > LONGLINE_THRESH:
            issues.append(('LONGLINE', i, s, rel))

    return issues


# ── Main ───────────────────────────────────────────────────────────────────────

SEVERITY = {'XREF': 0, 'ARTIFACT': 1, 'SYNOPSIS': 2, 'FUNCDEF': 3, 'BROKEN_ANCHOR': 4, 'LONGLINE': 5}


def main() -> None:
    args    = sys.argv[1:]
    summary = '--summary' in args
    args    = [a for a in args if a != '--summary']

    only: set[str] | None = None
    for a in list(args):
        if a.startswith('--only=') or a.startswith('--only'):
            val = a.split('=', 1)[-1] if '=' in a else args[args.index(a) + 1]
            only = set(v.strip().upper() for v in val.split(','))
            args = [x for x in args if x not in (a, val)]

    if args:
        paths = [os.path.abspath(a) for a in args if a.endswith('.md')]
    else:
        paths = sorted(
            os.path.join(root, f)
            for root, _, files in os.walk(DOCS)
            for f in files
            if f.endswith('.md')
        )

    all_issues: list[Issue] = []
    for path in paths:
        all_issues.extend(scan_file(path, DOCS))

    if only:
        all_issues = [iss for iss in all_issues if iss[0] in only]

    # Group by file, sort by (file, lineno)
    all_issues.sort(key=lambda x: (x[3], x[1]))

    if summary:
        from collections import Counter
        by_cat = Counter(iss[0] for iss in all_issues)
        by_file = len({iss[3] for iss in all_issues})
        print(f"{'Category':<12} {'Count':>6}")
        print('-' * 20)
        for cat in sorted(SEVERITY, key=SEVERITY.get):
            if cat in by_cat:
                print(f'{cat:<12} {by_cat[cat]:>6}')
        print('-' * 20)
        print(f"{'TOTAL':<12} {len(all_issues):>6}  ({by_file} files)")
        return

    # Detailed output
    current_file = None
    for cat, lineno, line, rel in all_issues:
        if rel != current_file:
            if current_file is not None:
                print()
            print(f'── {rel}')
            current_file = rel
        snippet = line[:120].rstrip()
        print(f'  {cat:<10} {lineno:>5}  {snippet}')

    print()
    from collections import Counter
    by_cat = Counter(iss[0] for iss in all_issues)
    parts = [f"{cat}={by_cat[cat]}" for cat in sorted(SEVERITY, key=SEVERITY.get) if cat in by_cat]
    print(f"Total: {len(all_issues)} issues  ({', '.join(parts)})")


if __name__ == '__main__':
    main()
